### ISSUE TITLE
node: symbol lookup error with Node.JS 0.8.0

### ISSUE THREAD

**Issue by violet-athena** [mariano/node-db-mysql#76]
When I tried to start my program it exited with this error:
"node: symbol lookup error: /usr/lib/node_modules/db-mysql/build/Release/mysql_bindings.node: undefined symbol: _ZNK2v85Value11IsUndefinedEv"

I'm using Ubuntu 12.04LTS and Node.JS installed via "n".

I tried reinstating the module and it compiled fine, but the error persists.

The same code works fine with Node.JS version 0.6.19

**Comment by cptroot** [comment]
Same here, using a Mac under OS 10.7.4, node.js v0.8.0. Also had it working fine before I updated.
If it helps, here is the full debug trace.

dyld: lazy symbol binding failed: Symbol not found: __ZNK2v85Value11IsUndefinedEv
  Referenced from: /Users/evan/FreeFlow/Merge Convert/node_modules/db-mysql/build/Release/mysql_bindings.node
  Expected in: flat namespace

dyld: Symbol not found: __ZNK2v85Value11IsUndefinedEv
  Referenced from: /Users/evan/FreeFlow/Merge Convert/node_modules/db-mysql/build/Release/mysql_bindings.node
  Expected in: flat namespace

Trace/BPT trap: 5

This looks like a linker error to me...

**Comment by cptroot** [comment]
For me it happens when I try to create a new database.
Also breaks on 0.8.1

**Comment by vanng822** [comment]
would be nice if this is fixed. Want to upgrade to 0.8 but got this issue (Mac).

**Comment by kmulvey** [comment]
+1 happens on node 0.8.2 (Fedora 17)

**Comment by Selvatico** [comment]
the same. i think author leaved development.

**Comment by mariano** [comment]
@Selvatico i did not leave development, if I were to leave I would make a clear announcement, and look for someone to take it over. Development is at a slower pace than usual because of my many responsibilities, though. I would love to see some pull requests coming ;)

**Comment by Selvatico** [comment]
@mariano sorry. i saw that last commit was 9 month ago... I would have helped but have no idea what this error means. I assuming that it occurs in all who upgrade to version 0.8.x. Maybe you will do small fix for new node version, because i choose you lib for stability and speed, but i can't upgrade my app becuase this error... I do not want to change the library. but if the decision will not be found will have to rewrite lots of code to a different lib. Thanks for fast reply.

**Comment by qraynaud** [comment]
I believe it is just that your module was compiled on 0.6. Simply npm remove & npm install again. It might solve the issue. The module is working fine on >0.8 for me.

**Comment by Percepter** [comment]
I installed db-mysql on my ubuntu 12.04 (with node-v0.8.8 on it) everything worked yesterday, and today (i made no changes on the system or my code) when i started node i got "  transfer: node: symbol lookup error: /home/nodejs/node_modules/db-mysql/build/Release/mysql_bindings.node: undefined symbol: _ZNK2v85Value11IsUndefinedEv "

**Comment by qraynaud** [comment]
Have you tried to npm remove & npm install again ? Might solve your issue. Be attentive to any compilation error you might get.

**Comment by Percepter** [comment]
yes, error is this there.

**Comment by qraynaud** [comment]
I was talking about a compilation error (during install) and not a runtime error there. Please try to uninstall / reinstall node-db-mysql & copy paste here the installation output if it is still doing the same.

**Comment by Percepter** [comment]
I reinstalled it and there where no errors, so i reinstalled also the the mysql_config and specify the mysql_configenvironment variable (export MYSQL_CONFIG=/usr/local/mysql/bin/mysql_config) 
and startet it with sudo node 'yourJsFile.js' and now it's running again.

**Comment by qraynaud** [comment]
Happy you found a solution. It didn't looked like a node-db-mysql bug. It looked like a linking issue. That's cool you found what was happening.

**Comment by Selvatico** [comment]
@Percepter thnx. your guide helps.

**Comment by himanshurobo** [comment]
I updated my ubuntu version 16.04 , It stop working . Previously, It was working with 14.04 version.
someone could help me whats the issue ?? and how to resolve it ??

**Comment by koerhunt** [comment]
Try to reinstall the "libuv" package, I have arch linux (manjaro) and this work for me:
`sudo pacman -S libuv`
